##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  guns配置  ###################
guns:
  swagger-open: false #是否开启swagger (true/false)
  kaptcha-open: ${kaptcha-open} #是否开启登录时验证码 (true/false)   线上 true
  session-open: ${session-open} #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)  线上 true
  file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 14400 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 7200 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 80

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: ${resource-auto-check} #是否检测文件变化,开发用true合适， 线上 false 


###################  spring配置  ###################
spring:
  redis:
    database: 0
    host: ${redis-host}
    port: ${redis-port}
    password: ${redis-password}
    timeout: 0
    pool:
     max-active: 8
     max-wait: -1
     max-idle: 8
     min-idle: 0
  profiles:
    active: produce # dev  produce
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: ${devtools-enabled} #是否开启开发者工具（true/false）  线上为 false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
   #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
