
##########################################################
###################  正式环境的profile  ###################
##########################################################
 spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/zww?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 199584
      db-name: zww
      filters: log4j,wall,mergeStat
      connectionInitSqls: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"

#flowable数据源和多数据源配置
 guns:
  flowable:
    datasource:
      url: jdbc:mysql://localhost:3306/zww-flowable?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 199584
  zww:
    datasource:
     url: jdbc:mysql://localhost:3306/zww?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
     username: root
     password: 199584

  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: localhost:3306/zww-flowable?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 199584

 logging:
  level.root: warn
  path: logs/
  file: zww.log



###################  aliyun配置  ###################
 aliyun:
  accessKey: LTAIibVdoyx3NRxN
  accessSecret: Jl7SGDipdHI8qtqGvplWxqUjOKfBCs
  mnsAccountEndPoint: http://1515324574307065.mns.cn-shenzhen.aliyuncs.com/
  ossBucketName: lanao
  sts: http://47.106.149.59:7080/app/oss/gettoken
  smsModelCode:
   reg: SMS_133510008
   find: SMS_133510008
   bind: SMS_133510008

################### dev prop配置 ########################

 redis-host: r-wz9af76938a6afa4.redis.rds.aliyuncs.com
 redis-port: 6379
 redis-password: Lz19958413
 kaptcha-open: true
 session-open: false
 resource-auto-check: false
 devtools-enabled: false